package main

import (
	"fmt"
	"sort"
	"strings"
)

func main() {
	lines := strings.Split(Puzzle, "\n")
	ids := make([]int, len(lines))
	id := 0

	for i, line := range lines {
		row := determineRow(line)
		col := determineCol(line)
		sId := row*8 + col
		fmt.Printf("Line %s, row %d, column %d, seat id %d\n", line, row, col, sId)

		ids[i] = sId
	}

	sort.Ints(ids)

	for i := 0; i < len(ids)-1; i++ {
		if ids[i+1]-ids[i] == 2 {
			id = ids[i] + 1
		}
	}

	fmt.Printf("Your seat is %d\n", id)
}

func determineRow(s string) int {
	rows := makeRange(0, 127)
	p := s[:7]
	for _, c := range p {
		l := len(rows) / 2
		if c == 'F' {
			rows = rows[:l]
		} else if c == 'B' {
			rows = rows[l:]
		}
	}

	return rows[0]
}

func determineCol(s string) int {
	cols := makeRange(0, 7)
	p := s[7:]

	for _, c := range p {
		l := len(cols) / 2
		if c == 'L' {
			cols = cols[:l]
		} else if c == 'R' {
			cols = cols[l:]
		}
	}

	return cols[0]
}

func makeRange(min, max int) []int {
	a := make([]int, max-min+1)
	for i := range a {
		a[i] = min + i
	}
	return a
}

const Puzzle = "FBBFBFFRRL\nBBFFBFBRRR\nBFBBFFFLRR\nFFBFFFBLLR\nBFBBBBBRLR\nFBFFFBFLRL\nBFBBBBFLRR\nFFBBBFBRRL\nFBFBBFBLRL\nBBFFFFBRRR\nFBBBBBBRRR\nFFBBFFBLLL\nBBFFFFFRRR\nBFFBFBFRLL\nBFBFFFBRLR\nFBBBFFFLRL\nBFBFBBFLRL\nBFFFBBBRRR\nFBFFBBFRRL\nBBFBFFFLLR\nFBBFBBBRLL\nBBFFBFBRLR\nBFFFFFBRLL\nBBFFFBBRRR\nFBFFBBFRLL\nFBBBBBFRRL\nBBFBFFFLRL\nBFBFBBBRLR\nFBBFBBBRRR\nBFBBBFFLLL\nBFFFFFFLLL\nBFBFFFBLRL\nFBBFBBBLLR\nBFFFBFBRLL\nFFBFFBFLRL\nFBFBFFBRLR\nBBFFFBBLLR\nBFFBFFFRRR\nFBFFBBBLLL\nBFBFFFFRLL\nFBFBBFFRRL\nBFBFBBBLLL\nBFBFBFFRLR\nFBBFBFFLRL\nBFFFFBBLLR\nFBBBFBBRRR\nFBBBFFFLRR\nFFBBBBFLRR\nBFFFFFFRRL\nBBFFFFFLRL\nBFFBFBFRLR\nFFBBBBBLLR\nFBFFBFBRLL\nBFBBFFBLRR\nBFFFFBFLLR\nFBBBBFFRLL\nFBBBFFBLLR\nBFFBBBFLLL\nFFBFBBBLLL\nBBFBFFFLRR\nFBFBFFFLRL\nBFFBBFFRRL\nFBFBFBBLRR\nFFBBFBBRLL\nFFBBFBFRLL\nBFFFBFBRRL\nBFBBBBFRLL\nBFFFBFBLLL\nBFFFBBBLLL\nFBBBBFBRRL\nBFBBFFBRLL\nBFBBFFFRLR\nFFBBBBFLLL\nFFBBFFBRLL\nFFBFBFFLRR\nFBBBFBBRRL\nFFBFBBBLRR\nBFBFFFFRRR\nBFFBBFBRRR\nBFFFFBBRLL\nBFFFBBFRRR\nBFFFBFBRLR\nFFBBBFFRRR\nBFFBFBFRRL\nFFBBBBBRLR\nFBBFBFBRRL\nFFBBBBBLRL\nFFBBFBBRRR\nBFFBBBFLLR\nFFBFBFFRRR\nBFBBFFBRRL\nBFBBFBBLLR\nFBBBFFBRLR\nBFFBBFFLLR\nFBBFFBFRRR\nFFBFFFBLRR\nFFFBBBBRRL\nFBBFBFBLLR\nFBBBBFFRRR\nFFFBBBBLRL\nFBBBFFBRRL\nBFBBFBFLRL\nFBBFBBFRRL\nFBBFBBFRLR\nBBFFBBFRLL\nBBFFFFBLLR\nFFBFFBFLLL\nFFBBFFBRRL\nFBBFFFBLLL\nFFFBBBBLLR\nFBBBFFBLLL\nFFBFBBFLLR\nFBBFBBFLRL\nBBFFBBFRLR\nFBFBBBBRLR\nBFBFBFFRRL\nBFBBFBBLLL\nFBFBBBBRRL\nFFBFBFBRLL\nBFFBBBFRRL\nBFFBFFBRLR\nFBFBBFBLRR\nFFBBFFFLRL\nBBFFFBBRLR\nFFBBBFFLLR\nFBFFFBBRRR\nBFFBBFBRRL\nBFBBFFFRLL\nFBFBBFBRLR\nFBBBBFFLLL\nFFBBFBFLLR\nBFFBBBFRLR\nBFFFBBBRLL\nBFBFBFBLRL\nBFFFFFFRRR\nFBFBFBBRRL\nBFBFFBFRRL\nFBFFFFFLRR\nFFBBBBFRRL\nFFBBBBBRRR\nBFBFFBBRRL\nBBFFFBFLRL\nFBBBBFBRLR\nBFBFFBFRRR\nFFBBBFBRLL\nFFBFFBBLLL\nBFBBBFBLRL\nBFFBBBBLLR\nFFBFBBFRLL\nBFFFBBBLRR\nBBFBFFFRRL\nBBFFBFFRLL\nBFBBFBFRRR\nFFBFBFBLRL\nBFBBFFBLLR\nFBBFBFBRLR\nFFBBBFBRLR\nFBFBBBFLRL\nFBFBBFFLRR\nFBBBFBBRLR\nFBFBBBFRRL\nBFFBBFBLRR\nFFFBBFBLLL\nBFBFFBFLRL\nFBBBBFFLLR\nFBFFFFFRRR\nFBFBFBFLLL\nBFBBFFFRRR\nBFBBBFBLRR\nBFBBFBFRLR\nFFBFFBFRLL\nBFBFBBFRRR\nBFBFFBFRLL\nBBFFBBBLLR\nFBFFBFBRLR\nFBBBFBFLRL\nBBFFBBFLLR\nBFBBBFFLRR\nFBBBFFFLLL\nFFBBFBFRRL\nFBFFBBFLLR\nFFBFFBBLRL\nFFBFBFBLLR\nFFFBBFFLLL\nBFBBFBBRRL\nBFBFBFBRLL\nBFFBFFFRLR\nBFFFBBFLLR\nFBFFFFFLLR\nFBFFFFBLLR\nFFFBBBFLRL\nFFBBFBBLRL\nFFBFBBBRRL\nFBBFBFBRRR\nBFFFFFBLLL\nBFBFBBBLRL\nBFFFFFBRRR\nFFBFBFFRLL\nBFFBFFBLLR\nBFFBFFFLLL\nBFBBBFFRLR\nBFBBBBBLLR\nFBFBFBBRLR\nBFFFBBBRLR\nFFFBBBFRLL\nBFBBBBBLLL\nFBBFFBBLLR\nBFBFFBBLLL\nFBFBBBBRRR\nFFBBFFFLLR\nBFFBFFBLRR\nBFFFFBFLRR\nFFBFFFBLLL\nFFBFBBFRRL\nFBBFFFFLRR\nFBFBFBBRLL\nBFFBFBFLRR\nBFFBBFBRLR\nBFFBFBBLRR\nBFFFBBBLLR\nFBFBFFBRRL\nBFBBBFFRRR\nBFBFFBBRLR\nFBFFBBFLRR\nFFFBBFFRRR\nBBFFBFFLRL\nFBFBBFBRRR\nFBFFFFBRLR\nFFBFFFFRLL\nFBBBFFBLRL\nFBBBBBBLLR\nBFFFBFBRRR\nFBBBBBFLLR\nBFFBFBBLLL\nFBBBFBFRRR\nFBBBFBFLLR\nFFBFBFFLRL\nBFFFBFBLRR\nFFFBFBBRRR\nBFBFBBFRLL\nFFBFBBBRLR\nBFBFBFFLRL\nFFBBFFBRRR\nBFBBFBBRLL\nFBFBBBFLLL\nBFBFFBFRLR\nFBBFBFFRLR\nBFFFFFFRLL\nBFFFFFBLRL\nFBBFBBFRRR\nFBBFBBFRLL\nFBFBFFFRLR\nFFBFFBFLLR\nFBBBFFFLLR\nBFBBBBBLRR\nFBFBBFFLLL\nFFFBBBBLRR\nFBBBBBBLRL\nFFBFFBBLRR\nFBBFFFFRRR\nBFBFBBFRLR\nFFBFBBFLRL\nBFBBFFFLLL\nBFBBBBFRRL\nFBBBFBFRRL\nFBFFBBBRLL\nFFBBFFFRLL\nFBFBBBBLRR\nFFBBBBFRLR\nFBFBBFFLRL\nFFBBFFBRLR\nFBBBFBFLRR\nFBFFFBFRLR\nFFBBBFFLLL\nFBFFBBFLRL\nFFBFFBFLRR\nFBFFBFFLLR\nFFFBBFFLRR\nFBBFFBBRRL\nBFBBBFBRRR\nBBFFBBBRRR\nBFFFBBFLRL\nFBFBFFBLRL\nFBBFFBFLLL\nBFFBBBFRRR\nBFFFBFFRRL\nFBFFFBFRRR\nFFBBFFBLRL\nBBFFFFBRLR\nFBFBBFBLLR\nFFBFFBFRLR\nBFBBFBFRLL\nFFBBFBFRRR\nBBFFBFBLLL\nFBBFBBBLLL\nFBBFFBFLRL\nFBFFFBFRRL\nFBBBFBBLRR\nFBBFFFFRRL\nFBBBBBFLRR\nFFBBFFFLLL\nBFBBBFBRLL\nFBFFFFBRLL\nBFBFBBFLLR\nFFBBBFFLRL\nFBBFBBBRLR\nBFBFBFFLLR\nBFFBBFBRLL\nFFFBBFFRRL\nFFBFFFFLRR\nBFFFFBFRLR\nFBFFFBBLLL\nFFBFBFFRRL\nFBFFFBBLRR\nFBFFBFFRLR\nFBBFBBBRRL\nFBFFBFBRRL\nFBFFFBFLLL\nBFFBFFBRLL\nBFFBBFBLLL\nBFFFFBBRRR\nFBFFFFBLLL\nFBBFBFFLRR\nFFFBBBFRRR\nBBFFFFFLLL\nBFFBFBBLRL\nBBFFFBBLRR\nFBFFBFBLLL\nBFBFFFBLLL\nBBFFBBFRRR\nFFBBFBBRRL\nFBBBBBBRRL\nFBFFFBFLLR\nBBFBFFFLLL\nBFFBBBBRRR\nFBBFFBBRRR\nFBBBBFFRLR\nFBBFBBFLRR\nFBBFFFFRLR\nBFBBBBFRLR\nFBFBFFBRLL\nBFFBFFFLLR\nFBFFBFBLLR\nFFFBBBFRLR\nFBBBFFBRRR\nBFFBBBBLRL\nBFFFFBBLLL\nBFFBBFFLRR\nBFFBFFFLRL\nFBBFBBBLRR\nFFFBBFBLRR\nFFBBBFBLRR\nFBFFFBBLRL\nFBFFBFFRRL\nFFBFBFFLLL\nFFBBBBBLRR\nFFBBFBFLLL\nFBFBFBFRLL\nBFFBBBFLRR\nFFBFBFBRRR\nFBBFFFBLRL\nFBBBFFBLRR\nBFBBBBFLRL\nBFBBFBFRRL\nFFBBBFFRLL\nBBFFFFFRLL\nBBFFFBBRRL\nFBBBFBBLLR\nFBBBBBBLRR\nFFBBFBFRLR\nFFBFFBFRRL\nFBBBBBFLRL\nBFBFBFBRRR\nBBFFBBFLLL\nBFFFBBFRLL\nFBFBBBBLRL\nBFFFBFFLRL\nFBBBFFFRRR\nBFFFFBFLLL\nBFFBBBFRLL\nFBFFFBBRLL\nFBFBFFBLLL\nFBBBBFBLRL\nFBBFBFFRRR\nFFFBBBBLLL\nFFBFBFBRLR\nBFBFBFBRRL\nBFBFBBBLRR\nFBFFFFFRLL\nBFBBBBBRRL\nFBBFFFFLLR\nFBBBBFBLLR\nFBBFFFFLRL\nFBBFBFBLLL\nBFFFFBBLRR\nFBBBBFFLRR\nBBFFFBFRRR\nFBFBBBFRLL\nBFFFFFBRRL\nBFFFFFFLRR\nFFBFFFBRLL\nFBFFBFFLLL\nBFBBFFBRRR\nBFBBFBFLRR\nBFBBFFBLLL\nFBBFFBFRLL\nBFBFBBFLRR\nFFBFFFFRLR\nFBFBBFBRLL\nFBFFBBBLRR\nFBBFBFBLRL\nFBFFBFBLRL\nFFBFFFFRRR\nBFFBBBBLLL\nBFFBFFFRRL\nBFBFBBBRRL\nBBFFFBFLLL\nFBBBFFBRLL\nBFFFFFFRLR\nFFFBBFBLRL\nBFBFBFBLLR\nFBFBFFFRRR\nFBFBFFBRRR\nBBFFFFBLRR\nBFBBBBFLLR\nFBFBFBFLRR\nFBBBBBFRLR\nBFFFBBFLRR\nBBFFBFBLRL\nBBFFFFFLRR\nFBFBFBFLLR\nFFFBBBBRRR\nBFFBBFFLLL\nFBBFBBBLRL\nBFFFBFFLRR\nBFBBBFBRLR\nFFBBFBBLLL\nBBFFBBBLLL\nBFFFBFBLLR\nFFBBBFBRRR\nBBFFFFFRLR\nFFBBBFFRRL\nFFBBFFBLLR\nFBBFBFFLLL\nFBBFFBBLLL\nBFFBFBBRLR\nFFBBFFFLRR\nBFFBFBBLLR\nFFBFFBBRRL\nFFBFBBBLLR\nBFFFBBFLLL\nFBBFFBFRLR\nBFFFBFFRRR\nFFFBBFFLLR\nFBFBBBFRRR\nBFFFFFBLRR\nFFBBFFFRRL\nFFBFBBBLRL\nFBBFFBFLRR\nBFFFFBBRLR\nFFBBBFBLLR\nFFFBBFBRLR\nBBFBFFFRLL\nFBFFBFFRLL\nFBBBBFBRLL\nBBFFFBBLRL\nBFFBFFFRLL\nFBFFFFFRRL\nBBFFBBBRLR\nBBFFFFFRRL\nBBFFBBBRLL\nBFFBFFBRRR\nBFBBFFFLLR\nBFFFBBFRLR\nFBBBFBFLLL\nBFBBFBBRLR\nFBBBFBBLLL\nBFBFBBBRLL\nBBFFFBFLLR\nBFBBFFFLRL\nFFBFBBFRRR\nFFBBBBBRRL\nBBFFBBFLRR\nFBFBBBFLRR\nFFBFFBBRRR\nFBBFFFBRLR\nBFBBBFFRRL\nFBFBFBFRLR\nFBBBBFBRRR\nFBBFFBBLRL\nBBFFFFBLRL\nFFFBBBBRLR\nFBFBBFFRLR\nBFBFFBBLLR\nBFFFFBBRRL\nBFBFFFBRLL\nFBFFBFBRRR\nFFBBFBBLLR\nBFFBBFFRRR\nFBFFFBBLLR\nFBFBBFBRRL\nFFBFFFFLLL\nBFFBBBBRLR\nBFFBBFBLRL\nBFFBFBBRRL\nFFBFFBBLLR\nFBBFFFBRRL\nBFBFFBBRLL\nFBFFFFBRRR\nBFFFFFFLLR\nFBFFBBFLLL\nFFFBBFBRLL\nBFBFFBFLLL\nBFBBFBBLRL\nBFFFBFFLLR\nFBFFFBBRRL\nBBFFFFBRLL\nFFBBBBBRLL\nFBFBFBFRRR\nBBFFBBFLRL\nFBBBBFBLLL\nBFBFBFFRRR\nFFBFBFFRLR\nBBFFBFBLRR\nBFBFFFFLRL\nBFFFBBFRRL\nFFBFBBBRRR\nFBFFFBFRLL\nBFFFFBFRRR\nBFBFBFFRLL\nFBBBFBFRLR\nBFFFFFBLLR\nBFBBBFBRRL\nBFFBBFFRLR\nFBBBFBBLRL\nBFFFBFFRLR\nBBFFFBFRLR\nBFFFBFFRLL\nFBBBBFFRRL\nBBFFBBFRRL\nBBFFBFFRRR\nBBFFBFFRRL\nFBBBBFBLRR\nBBFFFBBRLL\nFBBFBFBLRR\nBFFBBFFLRL\nBFBBBFBLLL\nBBFFBFBRLL\nFFBFFFBRLR\nBBFFBBBLRL\nFFBBFBBLRR\nFFBBBFBLLL\nBFFBFFFLRR\nFFBFBFFLLR\nFFBFFBBRLL\nBFBBBBBLRL\nBBFFFBFLRR\nBFBFBFFLRR\nBFFBFBFLLL\nFFBFFFFRRL\nFFBBBBFRLL\nFBFBFBBLRL\nBBFFFBFRRL\nFFBFFBFRRR\nFBBFFBBRLR\nFBBFBFBRLL\nBFBFBFBRLR\nBFFBFFBLRL\nBFBBFFBRLR\nFBFBFFFLLR\nBFFFFFFLRL\nFBBFBBFLLL\nFFBBBFBLRL\nBFBFBBFLLL\nBBFFFBFRLL\nFBFBFFBLRR\nFBBBFFFRLR\nBFBBBFFLRL\nFFBBFFBLRR\nBBFFBFFLLR\nFBFFBFFRRR\nFBFFBBBRLR\nBFBFBFBLRR\nBFFBBBBRLL\nFBFFFFBLRL\nFBBFBFFLLR\nFBFBFFFLRR\nFBBBBBBRLL\nFBFFBBBRRR\nFBBFFBBLRR\nBFFFBFBLRL\nFBBFFFFRLL\nBFBFFBBRRR\nBBFFBBBLRR\nBFBFFFBLLR\nFBFBFBBRRR\nFFFBBBFLLR\nBFBFFFFLLL\nFBFFBBBLRL\nFBFBFBBLLL\nFFBFFFFLRL\nFBFBBBBLLR\nFBFBFBFLRL\nFBBBFBFRLL\nFBFBFFFRRL\nBBFFBBBRRL\nBBFFFFBLLL\nFBFFBBBRRL\nBFBFFFBRRL\nBBFFFFBRRL\nBFBFFBBLRR\nBFFBFFBRRL\nFFBFBFBRRL\nFFFBBFBRRR\nBBFFFBBLLL\nFBFBBFFRLL\nBFFFBFFLLL\nBFFBFBFLRL\nFBBBBBFRLL\nFBFBBBFLLR\nFFBBFFFRRR\nFBBBBBBLLL\nBFBFBBFRRL\nFBFBFBFRRL\nBFBFFFFRLR\nFFFBBFFRLR\nFFBBBFFRLR\nFFFBBFBRRL\nFBFFFFFRLR\nFBFFBBFRLR\nFFBFFFBLRL\nBFBFFFFLRR\nFFBFFFFLLR\nFFBBFFFRLR\nBFBFFFBLRR\nFBBBBBFRRR\nBFFBBBBRRL\nFFFBBFFLRL\nFBFFBFBLRR\nFBBFFBFRRL\nFBBFBFFRLL\nFFBFBBBRLL\nBFFFBBBLRL\nBFFBFBBRRR\nFBBBBBBRLR\nBFBFBBBRRR\nBBFFBFFRLR\nFBBBFFFRRL\nFFBBBBFRRR\nBFBBBFBLLR\nFFFBBBFRRL\nFFFBBBBRLL\nFBBBFBBRLL\nBFFFFFBRLR\nBFBFBBBLLR\nBFBFFBBLRL\nFBBFFFBRRR\nBFBBFBBLRR\nFBBFFBFLLR\nFBFBBBBRLL\nBFFBBFFRLL\nFFBBFBBRLR\nBFBFFBFLLR\nBFBBBFFLLR\nFBBFBBFLLR\nBFBBFBFLLR\nBFFBFBFRRR\nBFBFBFBLLL\nFBFFFFFLLL\nFFBFFFBRRL\nFBFFBBFRRR\nBBFFBFBRRL\nFBFFBFFLRR\nFBFBBFFRRR\nBFFFBBBRRL\nBFBFBFFLLL\nBFBFFFFLLR\nFBBBBBFLLL\nFFBFFBBRLR\nFFBBBBBLLL\nBFFBBBFLRL\nFFBBFBFLRL\nFFFBBBFLLL\nBFFFFBFLRL\nFBBFFFBLLR\nFBFBBBFRLR\nBBFFBFBLLR\nBFBBBBFRRR\nFBFBFFFRLL\nFBFBBFBLLL\nFBFBFFFLLL\nFFBFBBFLLL\nBFBFFFFRRL\nFFFBBFBLLR\nBFFBBFBLLR\nFFBFBFBLLL\nFBFBBFFLLR\nFFBFBFBLRR\nBFFBFBFLLR\nBFBBBBBRRR\nFBBFFFBLRR\nFBBFFFFLLL\nFFBBFBFLRR\nBBFFFFFLLR\nBFBBFBFLLL\nBFFFFBBLRL\nFBFFFFBLRR\nFFBBBFFLRR\nFFFBBFFRLL\nBFFBBBBLRR\nFBFFBBBLLR\nFFBFFFBRRR\nFBFFFFFLRL\nBFFFFBFRRL\nBFFFFBFRLL\nBFBFFBFLRR\nBFBBBFFRLL\nBFBBFBBRRR\nBBFBFFFRLR\nBBFFBFFLRR\nFFBFBBFRLR\nBFBBBBFLLL\nFBFFFBBRLR\nBFBBBBBRLL\nBBFFBFFLLL\nFBFFBFFLRL\nFBFBFBBLLR\nBFFBFFBLLL\nFFBBBBFLRL\nFBFBFFBLLR\nFFFBBBFLRR\nFBBBFFFRLL\nBFFBFBBRLL\nFFBFBBFLRR\nBFBBFFFRRL\nFFBBBBFLLR\nFBBFFFBRLL\nFBFBBBBLLL\nFBFFFBFLRR\nFBBBBFFLRL\nBFBFFFBRRR\nFBBFFBBRLL\nFBFFFFBRRL"
